apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::851725312153:role/eksctl-project-eks-nodegroup-my-no-NodeInstanceRole-rQl1tAgb6CpB
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::851725312153:role/eks-oidc-github-action
      username: github-oidc-auth-user   
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-18T11:18:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1434"
  uid: be3916ae-836e-4985-b5af-0bb30573855d
